import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import SkeletonCard from "../components/SkeletonCard";
import HotelCard from "../components/HotelCard";

export const getStaticProps = async () => {
  const res = await fetch(
    "https://63b44f0d9f50390584ad1c20.mockapi.io/api/v1/hotels"
  );
  const data = await res.json();
  return {
    props: { hotels: data },
  };
};

export default function Home({ hotels }) {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    if (hotels) {
      setTimeout(() => {
        setLoading(false);
      }, 3000);
    }
  }, [hotels]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-full mx-auto px-8 sm:px-16">
        <h1 className="text-3xl font-bold underline"> Home Page</h1>
        <div className="flex flex-wrap gap-6">
          {loading ? (
            <SkeletonCard />
          ) : (
            hotels.map((hotel) => (
              <HotelCard hotel={hotel}/>
            ))
          )}
        </div>
      </main>
    </>
  );
}
